#!/bin/sh
set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PACKAGE_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
ENV_FILE=${ORACLE21C_ENV_FILE:-$PACKAGE_ROOT/.env}

if [ -f "$ENV_FILE" ]; then
  . "$ENV_FILE"
fi

PRIMARY_DMP_HOST_PATH=${ORACLE21C_DMP_HOST_PATH:-/data/oracle-recovery/oracle21c/dmp}

export ORACLE21C_MODE=${UTF_ORACLE21C_MODE:-auto}
export ORACLE21C_IMAGE=${UTF_ORACLE21C_IMAGE:-${ORACLE21C_IMAGE:-softwareplant/oracle:clean-21.3.0-ee}}
export ORACLE21C_IMAGE_TAR=${UTF_ORACLE21C_IMAGE_TAR:-${ORACLE21C_IMAGE_TAR:-}}
export ORACLE21C_CONTAINER=${UTF_ORACLE21C_CONTAINER:-oracle-recovery-oracle21c-utf8}
export ORACLE21C_HOSTNAME=${UTF_ORACLE21C_HOSTNAME:-oracle21c-utf8}
export ORACLE21C_NETWORK=${UTF_ORACLE21C_NETWORK:-${ORACLE21C_NETWORK:-oracle-recovery-net}}
export ORACLE21C_LISTENER_PORT=${UTF_ORACLE21C_LISTENER_PORT:-1523}
export ORACLE21C_EM_PORT=${UTF_ORACLE21C_EM_PORT:-5502}
export ORACLE21C_SID=${UTF_ORACLE21C_SID:-ORCLUTF8}
export ORACLE21C_PDB=${UTF_ORACLE21C_PDB:-ORCLPDBUTF8}
export ORACLE21C_PASSWORD=${UTF_ORACLE21C_PASSWORD:-${ORACLE21C_PASSWORD:-}}
export ORACLE21C_CHARACTERSET=${UTF_ORACLE21C_CHARACTERSET:-AL32UTF8}
export ORACLE21C_NCHAR_CHARACTERSET=${UTF_ORACLE21C_NCHAR_CHARACTERSET:-AL16UTF16}
export ORACLE21C_ENABLE_ARCHIVELOG=${UTF_ORACLE21C_ENABLE_ARCHIVELOG:-false}
export ORACLE21C_DATA_ROOT=${UTF_ORACLE21C_DATA_ROOT:-/data/oracle-recovery/oracle21c-utf8}
export ORACLE21C_ORADATA_HOST_PATH=${UTF_ORACLE21C_ORADATA_HOST_PATH:-$ORACLE21C_DATA_ROOT/oradata}
export ORACLE21C_DMP_HOST_PATH=${UTF_ORACLE21C_DMP_HOST_PATH:-$PRIMARY_DMP_HOST_PATH}
export ORACLE21C_TABLESPACE_HOST_PATH=${UTF_ORACLE21C_TABLESPACE_HOST_PATH:-$ORACLE21C_DATA_ROOT/tablespaces}
export ORACLE21C_MEMORY_LIMIT=${UTF_ORACLE21C_MEMORY_LIMIT:-${ORACLE21C_MEMORY_LIMIT:-}}
export ORACLE21C_SHM_SIZE=${UTF_ORACLE21C_SHM_SIZE:-${ORACLE21C_SHM_SIZE:-1g}}
export ORACLE21C_STARTUP_TIMEOUT_SECONDS=${UTF_ORACLE21C_STARTUP_TIMEOUT_SECONDS:-${ORACLE21C_STARTUP_TIMEOUT_SECONDS:-1800}}
export ORACLE21C_INIT_SGA_SIZE=${UTF_ORACLE21C_INIT_SGA_SIZE:-${ORACLE21C_INIT_SGA_SIZE:-}}
export ORACLE21C_INIT_PGA_SIZE=${UTF_ORACLE21C_INIT_PGA_SIZE:-${ORACLE21C_INIT_PGA_SIZE:-}}
export ORACLE21C_INIT_CPU_COUNT=${UTF_ORACLE21C_INIT_CPU_COUNT:-${ORACLE21C_INIT_CPU_COUNT:-}}
export ORACLE21C_INIT_PROCESSES=${UTF_ORACLE21C_INIT_PROCESSES:-${ORACLE21C_INIT_PROCESSES:-}}
export ORACLE21C_TEMP_AUTO_EXTEND=${UTF_ORACLE21C_TEMP_AUTO_EXTEND:-${ORACLE21C_TEMP_AUTO_EXTEND:-true}}
export ORACLE21C_TEMPFILE_NAME=${UTF_ORACLE21C_TEMPFILE_NAME:-temp_recovery_utf8_01.dbf}
export ORACLE21C_TEMPFILE_INITIAL_SIZE=${UTF_ORACLE21C_TEMPFILE_INITIAL_SIZE:-${ORACLE21C_TEMPFILE_INITIAL_SIZE:-20G}}
export ORACLE21C_TEMPFILE_NEXT_SIZE=${UTF_ORACLE21C_TEMPFILE_NEXT_SIZE:-${ORACLE21C_TEMPFILE_NEXT_SIZE:-2G}}
export ORACLE21C_TEMPFILE_MAX_SIZE=${UTF_ORACLE21C_TEMPFILE_MAX_SIZE:-${ORACLE21C_TEMPFILE_MAX_SIZE:-100G}}
export ORACLE21C_ENV_FILE=/dev/null

exec sh "$SCRIPT_DIR/start-oracle21c.sh"
